use std::collections::BTreeMap;
use std::error::Error;
use std::fs;
use std::path::Path;

use time::OffsetDateTime;

use super::rig_client;

// Generated by build.rs from src/rig/r-versions.json:
// - EMBEDDED_RELEASES_FETCHED_AT: &str
// - embedded_releases() -> Vec<RRelease>
include!(concat!(env!("OUT_DIR"), "/r_version_releases.rs"));

#[derive(serde::Deserialize, serde::Serialize)]
struct RRelease {
    version: String,
    date: String,
}

#[derive(serde::Deserialize)]
struct RigAvailableRelease {
    #[serde(default)]
    name: String,
    version: String,
    #[serde(default)]
    semver: Option<String>,
    date: Option<String>,
}

#[derive(serde::Deserialize, serde::Serialize)]
struct CachedReleases {
    fetched_at: String,
    releases: Vec<RRelease>,
}

pub(crate) fn select_installed_r_on<'a>(
    installed: &'a [rig_client::InstalledR],
    exclude_newer: &str,
) -> Result<Option<&'a rig_client::InstalledR>, Box<dyn Error>> {
    let releases = releases_for(exclude_newer)?;
    Ok(latest_installed_release_on(
        installed,
        &releases,
        exclude_newer,
    ))
}

fn releases_for(exclude_newer: &str) -> Result<Vec<RRelease>, Box<dyn Error>> {
    if exclude_newer <= EMBEDDED_RELEASES_FETCHED_AT {
        return Ok(embedded_releases());
    }

    Ok(cached_releases(exclude_newer)?.releases)
}

fn latest_installed_release_on<'a>(
    installed: &'a [rig_client::InstalledR],
    releases: &[RRelease],
    exclude_newer: &str,
) -> Option<&'a rig_client::InstalledR> {
    let release_dates = release_dates(releases);
    installed
        .iter()
        .filter_map(|installed| {
            let parts = version_parts(&installed.version)?;
            let date = release_dates.get(installed.version.as_str())?;
            if *date <= exclude_newer {
                Some((parts, installed))
            } else {
                None
            }
        })
        .max_by_key(|(parts, _installed)| *parts)
        .map(|(_parts, installed)| installed)
}

fn release_dates(releases: &[RRelease]) -> BTreeMap<&str, &str> {
    let mut dates = BTreeMap::new();
    for release in releases {
        dates
            .entry(release.version.as_str())
            .and_modify(|previous: &mut &str| {
                if release.date.as_str() < *previous {
                    *previous = release.date.as_str();
                }
            })
            .or_insert(release.date.as_str());
    }
    dates
}

fn cached_releases(exclude_newer: &str) -> Result<CachedReleases, Box<dyn Error>> {
    let path = crate::runtime::ir_cache_dir()?
        .join("rig")
        .join("releases.json");
    if path.exists() {
        let json = fs::read_to_string(&path)
            .map_err(|e| format!("failed to read `{}`: {e}", path.display()))?;
        let cache = parse_cached_releases_json(&json, &path)?;
        if cache.fetched_at.as_str() >= exclude_newer {
            return Ok(cache);
        }
    }

    let cache = CachedReleases {
        fetched_at: utc_today_string(),
        releases: fetch_releases()?,
    };
    let json = serde_json::to_string_pretty(&cache)
        .map_err(|e| format!("failed to serialize cached R release metadata: {e}"))?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("failed to create `{}`: {e}", parent.display()))?;
    }
    fs::write(&path, json).map_err(|e| format!("failed to write `{}`: {e}", path.display()))?;
    Ok(cache)
}

fn parse_cached_releases_json(json: &str, path: &Path) -> Result<CachedReleases, Box<dyn Error>> {
    let cache: CachedReleases = serde_json::from_str(json)
        .map_err(|e| format!("failed to parse `{}` JSON: {e}", path.display()))?;
    if !is_iso_date(&cache.fetched_at) {
        return Err(format!(
            "`{}` has an invalid `fetched_at` date; expected YYYY-MM-DD",
            path.display()
        )
        .into());
    }
    for release in &cache.releases {
        if version_parts(&release.version).is_none() {
            return Err(format!(
                "`{}` has an invalid R release version `{}`; expected X.Y.Z",
                path.display(),
                release.version
            )
            .into());
        }
        if !is_iso_date(&release.date) {
            return Err(format!(
                "`{}` has an invalid R {} release date; expected YYYY-MM-DD",
                path.display(),
                release.version
            )
            .into());
        }
    }
    Ok(cache)
}

fn fetch_releases() -> Result<Vec<RRelease>, Box<dyn Error>> {
    let json = String::from_utf8(rig_client::output(&["available", "--all", "--json"])?)
        .map_err(|e| format!("`rig available --all --json` returned non-UTF-8 output: {e}"))?;
    let available: Vec<RigAvailableRelease> = serde_json::from_str(&json)
        .map_err(|e| format!("failed to parse `rig available --all --json` JSON: {e}"))?;

    let mut by_version = BTreeMap::new();
    for release in available {
        if matches!(release.name.as_str(), "devel" | "next") {
            continue;
        }
        let version = release.semver.as_deref().unwrap_or(&release.version);
        let Some((major, _minor, _patch)) = version_parts(version) else {
            continue;
        };
        if major < 3 {
            continue;
        }
        let Some(date) = release.date.as_deref().and_then(iso_date_prefix) else {
            continue;
        };
        by_version
            .entry(version.to_string())
            .and_modify(|previous: &mut String| {
                if date < previous.as_str() {
                    *previous = date.to_string();
                }
            })
            .or_insert_with(|| date.to_string());
    }

    let releases = by_version
        .into_iter()
        .map(|(version, date)| RRelease { version, date })
        .collect::<Vec<_>>();
    if releases.is_empty() {
        return Err("`rig available --all --json` did not report any R releases".into());
    }
    Ok(releases)
}

fn version_parts(value: &str) -> Option<(u64, u64, u64)> {
    let mut parts = value.split('.');
    let major = parts.next()?.parse().ok()?;
    let minor = parts.next()?.parse().ok()?;
    let patch = parts.next()?.parse().ok()?;
    if parts.next().is_some() {
        return None;
    }
    Some((major, minor, patch))
}

fn iso_date_prefix(value: &str) -> Option<&str> {
    let date = value.get(..10)?;
    if is_iso_date(date) {
        Some(date)
    } else {
        None
    }
}

fn is_iso_date(value: &str) -> bool {
    let bytes = value.as_bytes();
    bytes.len() == 10
        && bytes[0].is_ascii_digit()
        && bytes[1].is_ascii_digit()
        && bytes[2].is_ascii_digit()
        && bytes[3].is_ascii_digit()
        && bytes[4] == b'-'
        && bytes[5].is_ascii_digit()
        && bytes[6].is_ascii_digit()
        && bytes[7] == b'-'
        && bytes[8].is_ascii_digit()
        && bytes[9].is_ascii_digit()
}

fn utc_today_string() -> String {
    let today = OffsetDateTime::now_utc().date();
    format!(
        "{:04}-{:02}-{:02}",
        today.year(),
        u8::from(today.month()),
        today.day()
    )
}
